DROP TABLE SCHEDULE;
DROP TABLE PLAYER;
DROP TABLE EVENET;
DROP TABLE NATION;

CREATE TABLE NATION (
    N_CODE NUMBER(3) PRIMARY KEY,
    N_NAME VARCHAR2(30)NOT NULL,
    N_PARTI_PERSON NUMBER DEFAULT 0,
    N_PRATI_EVENT NUMBER,
    N_PREY_RANKD NUMBER,
    N_CURR_TANK NUMBER
);
CREATE TABLE EVENT (
    E_CODE NUMBER PRIMARY KEY,
    E_NAME VARCHAR2(30) NOT NULL,
    E_FIRST_YEAR NUMBER(4),
    E_INFO VARCHAR2(100)
);
CREATE TABLE PLAYER (
    P_CODE NUMBER(3) PRIMARY KEY,
    P_NAME VARCHAR2(30) NOT NULL,
    N_CODE NUMBER(3) REFERENCES NATION(N_CODE),
    E_CODE NUMBER REFERENCES EVENT(E_CODE),
    P_RANKN NUMBER,
    P_AGE NUMBER(3)
);
CREATE TABLE SCHDULE (
    N_CODE NUMBER(3)REFERENCES NATION(N_CODE),
    E_CODE NUMBER REFERENCES EVENT(E_CODE),
    S_START_DATE DATE,
    S_END_DATE DATE,
    S_INFO VARCHAR2(100),
    PRIMARY KEY(N_CODE, E_CODE)
);