-- 1. DESCRIBE = DESC
-- 테이블 구조 확인
DESC BANK;

-- 2. 테이블 데이터 검색
-- DQL : DATA QUERY LANGUAGE
-- SELECT 보고싶은칼럼 FROM 테이블;
-- SELECT 보고싶은칼럼 FROM 테이블 WHERE 조건식;
SELECT BANK_CODE FROM BANK;
SELECT BANK_CODE, BANK_NAME FROM BANK;

-- 3. 사용자 제약조건이 저장된 DD(DATA DICTIONARY)
-- USER_CONSTRAINTS 테이블
SELECT CONSTRAINT_NAME, TABLE_NAME FROM USER_CONSTRAINTS;
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CUSTOMER';

-- 제약조건 관리
-- 1. 제약조건 삭제
-- CUSTOMER 테이블의 기본키를 제거하시오.
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_PK;

-- 2. 제약조건의 추가
-- CUSTOMER 테이블의 NO 칼럼에 CUSTMOER_PK 라는 이름의 PRIMARY KEY 제약조건을 추가하시오.
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY(NO);

-- 3. 제약조건의 비활성화
-- CUSTOMER 테이블의 CUSTOMER_PK 비활성화
ALTER TABLE CUSTOMER DISABLE CONSTRAINT CUSTOMER_PK;

-- 4. 제약조건의 활성화
-- CUSTOMER 테이블의 CUSTOMER_PK 활성화
ALTER TABLE CUSTOMER ENABLE CONSTRAINT CUSTOMER_PK;