DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
    DEPT_NO NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(15) NOT NULL,
    LOCATION VARCHAR2(15) NOT NULL
);
CREATE TABLE EMPLOYEE (
    EMP_NO NUMBER DEFAULT 1001 PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    DEPART NUMBER REFERENCES DEPARTMENT(DEPT_NO),
    POSITION VARCHAR2(20),
    GENDER CHAR(2),
    HIRE_DATE DATE,
    SALARY NUMBER
);

INSERT INTO DEPARTMENT
VALUES (1, '영업부', '대구');
INSERT INTO DEPARTMENT
VALUES (2, '인사부', '서울');
INSERT INTO DEPARTMENT
VALUES (3, '총무부', '대구');
INSERT INTO DEPARTMENT
VALUES (4, '기획부', '서울');

-- DB에서 날짜로 인식되는 리터럴(표현법: -, /)
-- 1. 20/10/22(오라클 표준 디폴트)
-- 2. 2020/10/22
-- 3. 20-10-22
-- 4. 2020-10-22

INSERT INTO EMPLOYEE
VALUES (1001, '구창민', 1, '과장', 'M', '95-05-01', 5000000);
INSERT INTO EMPLOYEE
VALUES (1002, '김민서', 1, '사원', 'M', '17-09-01', 2500000);
INSERT INTO EMPLOYEE
VALUES (1003, '이은영', 2, '부장', 'F', '90-09-01', 5500000);
INSERT INTO EMPLOYEE
VALUES (1004, '한성일', 2, '과장', 'M', '93-04-01', 5000000);
COMMIT;

UPDATE DEPARTMENT SET LOCATION = '세종'
WHERE DEPT_NO = 4;
COMMIT;

UPDATE EMPLOYEE SET SALARY = SALARY + 300000
WHERE EMP_NO = 1002;
COMMIT;

DELETE FROM DEPARTMENT WHERE DEPT_NO = 3;
COMMIT;

SELECT DEPT_NO, DEPT_NAME, LOCATION FROM DEPARTMENT;
SELECT EMP_NO, NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY FROM EMPLOYEE;